apiVersion: manifest.k8s.io/v1alpha1
kind: Manifest
metadata:
  name: ldap-phpldapadmin
description: LDAP Deployment with phpldapadmin UI.
packages:
  - ldap/
  - phpldapadmin/
patches:
  - patch.yaml
